### ISSUE TITLE
department data index

### ISSUE THREAD

**Issue by udrysa** [cityofsandiego/seaboard#216]
on the left hand side where a user can browse data and we have data listed by city category (infrastructure, management, etc) there is also the option of seeing it by department.  that function didn't work for me this morning.  for example, it said that DSD had "0" data. and when i clicked on DSD nothing came up.  it appeared to be the case for several other departments.

**Comment by andrell81** [comment]
If you make a selection in either category or department, the other section changes based on your selection. For example, if I select the category of Public Safety, then Development Services Department would have 0 datasets because none of the datasets they released fall into the Public Safety category.

That most likely was the problem, but if it happens again, send me a screenshot so I can better troubleshoot.
